### ISSUE TITLE
 moderation-docs, add the importance of adding the right Matrix ID

### ISSUE THREAD

**Issue by Timmaks** [FOSDEM/moderation-docs#2]
I suggest to add a line to emphasize the importance to add the correct matrix ID

**Comment by pieterdp** [comment]
Welcome to make a PR!

**Comment by pieterdp** [comment]
I've added something.

**Comment by Timmaks** [comment]
Great, i think this issue can be closed

**Comment by Timmaks** [comment]
> Welcome to make a PR!

You where faster ;-)
